name: Pixel Bazaar
favicon: null
layout_spectrum: 0.00169
typography_spectrum: 0.63766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6578741087578237
  lightness: 0.8634657973889261
  saturation: 0.33259006682783365
  rhythmicContrast: 0.026342032477259636
purpose: []
